// This file is autogenerated by Firebase Studio. Do not edit manually.

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';

const firebaseConfig = {
  apiKey: 'TODO: YOUR API KEY',
  authDomain: 'TODO: YOUR AUTH DOMAIN',
  projectId: 'TODO: YOUR PROJECT ID',
  storageBucket: 'TODO: YOUR STORAGE BUCKET',
  messagingSenderId: 'TODO: YOUR MESSAGING SENDER ID',
  appId: 'TODO: YOUR APP ID',
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export {app, auth, db, storage};
