// This file is autogenerated by Firebase Studio. Do not edit manually.

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';
import {getStorage} from 'firebase/storage';

const firebaseConfig = {
  "projectId": "labbridge-medfusion",
  "appId": "1:1099034823548:web:61c80294903e35b85bf2f9",
  "storageBucket": "labbridge-medfusion.firebasestorage.app",
  "apiKey": "AIzaSyCpxk53kSZ3rosR7FFIP6HzzJBXO9zupvA",
  "authDomain": "labbridge-medfusion.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1099034823548"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

export {app, auth, db, storage};
